---
#
# Ansible managed
#
repository:
  description: Logstash for Linux.
  homepage: https://buluma.github.io/
  topics: web, system, monitoring, logging, logs, elk, logstash, ansible, molecule, tox, playbook
