---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check logstash version
      ansible.builtin.command:
        cmd: /usr/share/logstash/bin/logstash --version
      register: logstash_test_one
      failed_when:
        - '"7" not in logstash_test_one.stdout'
      changed_when: false
