---
#
# Ansible managed
#

name: Auto Merge Dependency Updates

on:
  - pull_request_target

permissions:
  contents: write
  pull-requests: write  # Needed if in a private repository

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto Merge Dependabot Updates
        uses: buluma/gh-action-auto-merge-dependabot-updates@1.0.7
        with:
          allowed-actors: buluma, dependabot-preview[bot], dependabot[bot]
